### ISSUE TITLE
How to run AlgoProject.java ?

### ISSUE THREAD

**Issue by failamir** [sjay93/String-Matching-Plagiarism-Detection#1]
I have to run it by standard steps, first javac the file
but error in action, 

.\AlgoProject.java:34: error: cannot find symbol
        LongestCommonSubsequence lcsSearch = new LongestCommonSubsequence();
        ^
  symbol:   class LongestCommonSubsequence
  location: class AlgoProject
.\AlgoProject.java:34: error: cannot find symbol
        LongestCommonSubsequence lcsSearch = new LongestCommonSubsequence();
                                                 ^
  symbol:   class LongestCommonSubsequence
  location: class AlgoProject
.\AlgoProject.java:35: error: cannot find symbol
                BoyerMoore bmSearch = new BoyerMoore();
                ^
  symbol:   class BoyerMoore
  location: class AlgoProject
.\AlgoProject.java:36: error: cannot find symbol
                KMP_String_Matching kmpSearch = new KMP_String_Matching();
                ^
  symbol:   class KMP_String_Matching
  location: class AlgoProject
.\AlgoProject.java:36: error: cannot find symbol
                KMP_String_Matching kmpSearch = new KMP_String_Matching();
                                                    ^
  symbol:   class KMP_String_Matching
  location: class AlgoProject
.\AlgoProject.java:37: error: cannot find symbol
                Naive naiveSearch = new Naive();
                ^
  symbol:   class Naive
  location: class AlgoProject
.\AlgoProject.java:37: error: cannot find symbol
                Naive naiveSearch = new Naive();
                                        ^
  symbol:   class Naive
  location: class AlgoProject
8 errors

what is the meaning cannot find symbol ?

**Comment by sjay93** [comment]
> I have to run it by standard steps, first javac the file
> but error in action,
> 
> .\AlgoProject.java:34: error: cannot find symbol
> LongestCommonSubsequence lcsSearch = new LongestCommonSubsequence();
> ^
> symbol: class LongestCommonSubsequence
> location: class AlgoProject
> .\AlgoProject.java:34: error: cannot find symbol
> LongestCommonSubsequence lcsSearch = new LongestCommonSubsequence();
> ^
> symbol: class LongestCommonSubsequence
> location: class AlgoProject
> .\AlgoProject.java:35: error: cannot find symbol
> BoyerMoore bmSearch = new BoyerMoore();
> ^
> symbol: class BoyerMoore
> location: class AlgoProject
> .\AlgoProject.java:36: error: cannot find symbol
> KMP_String_Matching kmpSearch = new KMP_String_Matching();
> ^
> symbol: class KMP_String_Matching
> location: class AlgoProject
> .\AlgoProject.java:36: error: cannot find symbol
> KMP_String_Matching kmpSearch = new KMP_String_Matching();
> ^
> symbol: class KMP_String_Matching
> location: class AlgoProject
> .\AlgoProject.java:37: error: cannot find symbol
> Naive naiveSearch = new Naive();
> ^
> symbol: class Naive
> location: class AlgoProject
> .\AlgoProject.java:37: error: cannot find symbol
> Naive naiveSearch = new Naive();
> ^
> symbol: class Naive
> location: class AlgoProject
> 8 errors
> 
> what is the meaning cannot find symbol ?

Download this project in any IDE. If not using IDE, first compile the java files other than Algoproject.java and then compile and run the Algoproject.java
